### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by treed593** [LukeMurphey/splunk-webhooks-input#3]
Is it possible to configure this to use an SSL certificate?

**Comment by LukeMurphey** [comment]
It doesn't yet but I'm planning on adding that in the next release. This is targeted towards the 1.1. release.

**Comment by treed593** [comment]
Is there an ETA for the 1.1 release?

**Comment by LukeMurphey** [comment]
I'm planning on releasing it by the end of the month.

**Comment by treed593** [comment]
Sorry to keep bothering you, but is there an update on this?

**Comment by LukeMurphey** [comment]
Sorry, I'm a little late. I have this started and hope to have it done soon.

**Comment by treed593** [comment]
Let me know if I can be of help

**Comment by LukeMurphey** [comment]
I have this nearly done (just in the final testing).

**Comment by LukeMurphey** [comment]
Do you mind trying the updated app and making sure that it works for you? See attached file.

You'll need to drop your certificate and key file (if you are using one) somewhere onto the file-system (like "/etc/apps/webhooks_input/data/mycertificate.pem"). Then, you will need to update the modular input configuration to point to the certificate.

Note that the UI will check to see if the file exists so you will need to upload the certificate before modifying the modular input.

[webhooks_input.tar.gz](https://github.com/LukeMurphey/splunk-webhooks-input/files/1443392/webhooks_input.tar.gz)

**Comment by treed593** [comment]
Everything seems to be working! I will report back if I notice anything strange

**Comment by LukeMurphey** [comment]
Awesome! I went ahead and pushed this onto Splunk-base too.

**Comment by treed593** [comment]
A nice to have would be for ca_certs
